### ISSUE TITLE
OOAnalyzer plugin

### ISSUE THREAD

**Issue by Trass3r** [cmu-sei/pharos#20] opened 2019-07-25 11:25 UTC
```
  File OOAnalyzer.py, line 797, in apply_all_structs
    c.id = self.__apply_class(c)
  File OOAnalyzer.py, line 573, in __apply_class
    u.apply()
  File OOAnalyzer.py, line 937, in apply
    idc.OpStroffEx(self.__ea, n, self.__cid, 0)
  File idc_bc695.py, line 107, in OpStroffEx
    def OpStroffEx(ea, n, strid, delta): return op_stroff(ea, n, strid, delta)
  File idc.py, line 1267, in op_stroff
    return ida_bytes.op_stroff(ea, n, path.cast(), 1, delta)
  File ida_bytes.py, line 1007, in op_stroff
    return _ida_bytes.op_stroff(*args)
TypeError: in method 'op_stroff', argument 1 of type 'insn_t const &'
```

Is it incompatible with the v7 API?

**Comment by Trass3r** [comment] 2019-07-26 00:20
Ok you need `idc.OpStroffEx(idautils.DecodeInstruction(self.__ea), n, self.__cid, 0)`.

**Comment by edmcman** [comment] 2019-07-26 14:31
Thanks for figuring this out.  Could you create a pull request?

**Comment by Trass3r** [comment] 2019-07-26 15:38
Won't work on older versions anymore though.

**Comment by edmcman** [comment] 2019-07-26 20:40
Hopefully @sei-jgennari can take a look at this when he gets back.  I don't know much about IDA scripting.

**Comment by Trass3r** [comment] 2019-07-28 10:34
By the way, setting the this pointer type is basically possible:
```py
# in __apply_method
      try:
         import ida_hexrays
         cfunc = ida_hexrays.decompile(method.start_ea)
      except Exception as e:
         print(e)
         return

      tif = cfunc.type
      funcdata = idaapi.func_type_data_t()
      tif.get_func_details(funcdata)
      if len(funcdata):
         tif = idaapi.tinfo_t()
         tif.get_named_type(idaapi.get_idati(), method.cls.ida_name)
         tif2 = tinfo_t()
         tif2.create_ptr(tif)
         funcdata[0].type = tif2
      function_tinfo = idaapi.tinfo_t()
      function_tinfo.create_func(funcdata)
      idaapi.apply_tinfo2(method.start_ea, function_tinfo, idaapi.TINFO_DEFINITE)
```

**Comment by lcytxw** [comment] 2019-07-29 05:25
This issue is easy.
--return ida_bytes.op_stroff(ea, n, path.cast(), 1, delta)
++return ida_bytes.op_stroff(long(ea), n, path.cast(), 1, delta)

**Comment by lcytxw** [comment] 2019-07-29 05:30
--idc.OpStroffEx(self.__ea, n, self.__cid, 0)
++idc.op_stroff(long(self.__ea), n, self.__cid, 0)

**Comment by sei-jgennari** [comment] 2019-07-29 17:43
Thanks for the comment and the fix. We are working on a patch that'll work for multiple versions of IDA.

**Comment by sei-jgennari** [comment] 2019-07-31 14:24
@Trass3r do you have any additional information about the JSON file you used to generate the stack trace above? I'm having trouble reproducing this issue in IDA 7.3.

**Comment by Trass3r** [comment] 2019-07-31 21:54
Hmm how could it depend on the json, isn't OpStroffEx called for every member access?

**Comment by sei-ccohen** [comment] 2019-07-31 22:28
Are you maybe using  different minor releases of IDA 7?  e.g. 7.2 versus 7.3?

**Comment by lcytxw** [comment] 2019-08-01 08:28
IDA 7.0 for Mac book pro cause this issue.

**Comment by Trass3r** [comment] 2019-10-03 11:27
Looks like there are also naming inconsistencies: https://github.com/Trass3r/pharos/commit/0d5685723242d1e4b358adbc3201ecc2f16b0789

**Comment by edmcman** [comment] 2019-10-03 12:19
@sei-jgennari

**Comment by edmcman** [comment] 2019-10-03 13:41
@Trass3r We're having trouble understanding what problem you're having.  Can you post the JSON file you are having trouble with?

**Comment by jeffgennari** [comment] 2019-10-03 14:43
@Trass3r Something was updated incorrectly. I restored the working version

**Comment by edmcman** [comment] 2019-10-03 14:44
Disregard my last comment.  We just pushed a fix.  Thanks.

**Comment by sei-ccohen** [comment] 2019-10-04 19:56
This was caused by some internal confusion about the syntax for the JSON file.  We think it's fixed now, but if we've blown it again, please feel free to reopen the issue.

**Closed by sei-ccohen** 2019-10-04 19:56 UTC
Labels: bug
