### ISSUE TITLE
Ghidra plugin uses wrong datatype

### ISSUE THREAD

**Issue by jtuu** [cmu-sei/pharos#112] opened 2020-06-26 15:48 UTC
Sometimes the Ghidra plugin uses the wrong datatype for a class member. For example it should've used the DWORD type but instead it used a type I had defined earlier called DIPROPDWORD. This is probably because it contains the name of the correct datatype.

![dfigoidfgj](https://user-images.githubusercontent.com/18546041/85875490-f20f5280-b7dc-11ea-9507-c752936f8179.png)

**Comment by sei-eschwartz** [comment] 2020-06-26 16:04
I suspect the problem is the `indexOf`.  Why is this not just a check of equality?

``` java
		return StreamSupport.stream(itr.spliterator(), true)
                  .filter(dt -> dt.getName().toUpperCase().indexOf(name.toUpperCase()) != -1).findAny();
```

**Comment by sei-eschwartz** [comment] 2020-06-26 16:09
Thanks for the report @jtuu.  It's clear where the problem is coming from.  I need to look more at how to fix it.  Presumably there is a reason that the check was done so loosely in the original implementation.  @sei-jgennari do you have recollection of this?

**Comment by sei-eschwartz** [comment] 2020-06-26 22:15
So I coincidentally "fixed" this on our internal branch, but it hasn't been tested very well yet.  But it should be fixed the next time we release new code.

If you want, I can set up a branch that contains this fix, but it might break something else.

**Comment by jtuu** [comment] 2020-06-27 02:20
That's great, thank you. No need to set up a branch, I can wait.

**Comment by jeffgennari** [comment] 2020-06-29 12:40
Careful with straight equality, the names don't always match word-for-word.

**Closed** 2020-07-10 20:19 UTC
Labels: bug, plugins
