### ISSUE TITLE
ooJson finds duplicate keys

### ISSUE THREAD

**Issue by dberlin** [cmu-sei/pharos#101] opened 2020-06-08 19:59 UTC
I have some large programs i am using ooanalyzer on, using the multi-step instructions.

They successfully complete inferencing, but when i extract with ^final and run oojson on the results, it finds duplicate keys:
```
ERROR: -g ['/root/pharos/share/prolog/oorules/oojson.P'],exportJSON('foo-output.P'),halt.: Duplicate key: '.?AV?$basic_ofstream@DU?$char_traits@D@std@@@std@@'
ERROR: In:
ERROR:   [12] dict_create(_138,structures,[cls_0x4103b0: ...,...|...])
ERROR:   [10] exportJSON('foo-output.P') at /root/pharos/share/prolog/oorules/oojson.P:383
ERROR:    [9] '<meta-call>'('<garbage_collected>') <foreign>
ERROR:    [8] catch(user:(...,...),error(duplicate_key('.?AV?$basic_ofstream@DU?$char_traits@D@std@@@std@@'),context(...,_286)),'$toplevel':true) at /usr/local/lib/swipl/boot/init.pl:482
ERROR:    [7] catch_with_backtrace('<garbage_collected>',error(duplicate_key('.?AV?$basic_ofstream@DU?$char_traits@D@std@@@std@@'),context(...,_342)),'<garbage_collected>') at /usr/local/lib/swipl/boot/init.pl:532
ERROR:
ERROR: Note: some frames are missing due to last-call optimization.
ERROR: Re-run your program in debug mode (:- debug.) to get more detail.
```

Running in debug mode, it is this function:

```
makeAllStructuresJson(Json):-
     % Get a list of Class IDs and sort them by the class ID.
     findall(ClsId, finalClass(ClsId, _, _, _, _, _), ClassIDList),
     sort(0, @=<, ClassIDList, SortedClassIDList),
     bagof(NameKey:ClsJson, makeOneClassInOrder(SortedClassIDList, NameKey, ClsJson), KVPairs),
     dict_create(Json, structures, KVPairs).
```

From what i can tell, what happens is that we get multiple finalClass entries with the same first argument  in the output:
```
finalClass(0xa5d638, 0xa5d638, 0x48, 0x48, 0, [0x4532e0, 0x453350, 0x453490, 0x4534b0, 0x4534d0, 0x4538f0, 0x453bf0, 0x453d60, 0x453d70, 0x453d80, 0x454d10, 0x455e90, 0x455f10]).
...

finalClass(0xa5d638, 0xa5d638, 0x40, 0x40, 0, [0x4564e0, 0x456600, 0x456690, 0x4569e0, 0x456ad0, 0x456f10, 0x457280]).
```

This in turn makes it very unhappy because when it pulls the names out, it ends up with the same names (generating duplicate keys)

**Comment by sei-ccohen** [comment] 2020-06-08 20:14
Very interesting.   You're correct that the results are not supposed to contain two classes with the same unique identifier (0xa5d638).  In this case, it's the address of a virtual function table, which we assigned to two classes, and we weren't supposed to do that either.   We've recently been working on some VFTable ownership rules related to multiple inheritance, and they're probably to blame.  Our C++ JSON module is more tolerant of duplicate keys than the Prolog JSON module so this bug only shows up when using the oojson.P step, although the results in the C++ exporter probably would have been discarded at some point.   We'll investigate the root cause some more.

Fortunately, using the "large file manual process" has saved you from having to start all over again! My recommendation is to simply edit the results file, and change the class identifier of the second class to something unique, and try running the JSON generation process again until it succeeds.  at this point, you're so close to done that you should just muscle through, and sort out what _really_ went wrong once you're in Ghidra or IDA Pro.  My guess is you'll find that there's a mildly confusing inheritance relationship between those classes.

**Comment by sei-eschwartz** [comment] 2020-06-08 20:18
Also, can you share the `.facts` and/or `.results` files?  That would help us figure out how that happened.

**Comment by dberlin** [comment] 2020-06-08 21:08
I'm happy to share the facts privately, let me know where to email them :)

(FWIW - the full facts take a long time to inference about 24-36 hours).

**Comment by sei-eschwartz** [comment] 2020-06-08 21:14
Send to eschwartz@cert.org please

Sent from Workspace ONE Boxer

On Jun 8, 2020 5:08 PM, Daniel Berlin <notifications@github.com> wrote:

I'm happy to share the facts privately, let me know where to email them :)

(FWIW - the full facts take a long time to inference about 24-36 hours).

**Comment by sei-eschwartz** [comment] 2020-06-09 11:53
We conclude very early on via reasonNOTMergeClasses_E that classes containing 0x4564e0 and 0x453350 are on different classes.

```
[eschwartz@pd4 ~]$ cat cncm-ed.log | fgrep factVFTableWrite | fgrep -e 4564e0 -e 453350 | sort
Concluding factVFTableWrite(0x453389, 0x453350, 0, 0xa5d638).
Concluding factVFTableWrite(0x4533c2, 0x453350, 0x18, 0xa08594).
Concluding factVFTableWrite(0x4533fc, 0x453350, 0, 0xa5d608).
Concluding factVFTableWrite(0x45650f, 0x4564e0, 0, 0xa5d638).
Concluding factVFTableWrite(0x456548, 0x4564e0, 0x18, 0xa08594).
Concluding factVFTableWrite(0x456569, 0x4564e0, 0, 0xa5d684).
```

My guess here is that 0x4564e0 and 0x453350 are both derived classes that share a common base class (and thus vftable).

It seems most likely to be then that this is a failure in reasonVFTableBelongsToClass/3, which we've changed recently.

**Comment by sei-eschwartz** [comment] 2020-06-09 12:22
I believe the problem is that I reversed the arguments of factVFTableOverwrite/4 in reasonVFTableBelongsToClass/3.  This caused us to mistakenly conclude that vftable 0xa5d638 was NOT overwritten and so was safe to use as an identifier.

**Comment by sei-eschwartz** [comment] 2020-06-09 19:41
I am fairly sure this fixed it, but I haven't gotten to the end of reasoning yet to confirm.

**Comment by sei-eschwartz** [comment] 2020-06-11 00:36
I was looking at this more, and I think the following three vftable writes are key:
``` prolog
Concluding factVFTableWrite(0x70d682, 0x70d650, 0, 0xa2c85c).
Concluding factVFTableWrite(0x70d147, 0x70d0a0, 0x16c, 0x9ae574).
Concluding factVFTableWrite(0x70d133, 0x70d0a0, 0, 0xa2c85c).
```

I think there are two possibilities:

- Both classes inherit from a common base class but don't override any functions.  Class 0x70d0a0 inherits from another class as well.
- Class 0x70d0a0 inherits from 0x70d650 and another class, and does not override any methods from 0x70d650.  Normally we'd see a vftable overwrite, but since the vftables are the same we might not.

In general, I think this means that some of our understanding of vftable "ownership" is wrong because the same vftable can appear in multiple classes, presumably when no methods are overridden.  In particular this rule from reasonVFTableBelongsToClass seems problematic:
```
        % If Method is a constructor, we can use factVFTableOverwrite to make sure that we are                                                                                                                                                                                                                                                                                              
        % actually installing this vftable for this class.  This only applies to constructors                                                                                                                                                                                                                                                                                               
        % because we have found destructors get optimized more. See the more detailed                                                                                                                                                                                                                                                                                                       
        % commentary in reasonMergeClasses_D regarding the bad_cast case in Lite/oo.                                                                                                                                                                                                                                                                                                        
        (not(factVFTableOverwrite(Method, VFTable, _OtherVFTable, Offset)),
         not(factNOTConstructor(Method)));
```

I'm not sure what to do about this in general, but in the short term when we use vftables for identifiers, we should make sure that the vftables "belong" to a single class.  I think doing this in general would probably break a lot of cases, but there's little harm in doing the check when we're deciding whether to use the vftable as a class identifier.

**Comment by sei-eschwartz** [comment] 2020-06-11 01:03
I'll try to merge this tomorrow but in the meantime: https://github.com/sei-eschwartz/pharos/commit/e4bd99bc408e7a77b8cce0dbcb8c353bd827c6ba

**Comment by dberlin** [comment] 2020-06-11 02:13
You are definitely correct that the MS compiler will reuse vftables if methods are not overridden.

See here for the equivalent in clang:
https://github.com/llvm/llvm-project/blob/master/clang/lib/AST/RecordLayoutBuilder.cpp#L2601

**Comment by dberlin** [comment] 2020-06-11 23:21
So at this point, we get one finalVFTable for each unique address, and one finalClass for each unique address, but oojson still errors out on duplicate keys. It is not obvious to me why. I'll send files over.

**Comment by sei-eschwartz** [comment] 2020-06-11 23:48
Please do send the files.  Hopefully at this point it's just a tweak to oojson.

**Comment by sei-eschwartz** [comment] 2020-06-12 00:01
I haven't been able to try this yet:

``` diff
diff --git a/share/prolog/oorules/oojson.P b/share/prolog/oorules/oojson.P
index 9acc5e7..ea89f23 100644
--- a/share/prolog/oorules/oojson.P
+++ b/share/prolog/oorules/oojson.P
@@ -23,6 +23,9 @@
 
 makeClassName(ClassId, Out):-
     finalClass(ClassId, VFTable, _, _, _, _),
+    % Only use the VFTable as the name if finalClass did.  This is necessary to ensure we don't
+    % use the same name for multiple classes which causes an error
+    ClassId=VFTable,
     % If there's a VFTable for the address, and the VFTable has a non-null name, then use that
     % name, otherwise make a class name from the address.
     finalVFTable(VFTable, _, _, _, RTTIName),
```

**Closed** 2020-06-12 20:05 UTC
Labels: bug, prolog
