### ISSUE TITLE
Ghidra plugin: java.lang.IllegalArgumentException: Paths must not end with /

### ISSUE THREAD

**Issue by gynt** [cmu-sei/pharos#160] opened 2021-01-25 17:57 UTC
I got a peculiar error using ghidra 9.3 dev and the latest release for the plugin from you.
It complains about a path ending with a slash, but there is no such slash in the JSON file I am trying to load.

Maybe this line is offending because it ends with `@@` ? 
`"name":".?AV?$_Ref_count_obj2@VFileStream@IO@System@@@std@@",`
And then the cause is the following line in which a `/` is appended because `ns.get()` returns empty?
https://github.com/cmu-sei/pharos/blob/master/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java#L468

```stacktrace
Paths must not end with /
java.lang.IllegalArgumentException: Paths must not end with /
	at ghidra.program.model.data.CategoryPath.<init>(CategoryPath.java:136)
	at ooanalyzer.OOAnalyzer.getCategoryPathFromClass(OOAnalyzer.java:473)
	at ooanalyzer.OOAnalyzer.selectType(OOAnalyzer.java:524)
	at ooanalyzer.OOAnalyzer.lambda$analyzeClasses$3(OOAnalyzer.java:365)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.WhileOps$1$1.accept(WhileOps.java:99)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at ooanalyzer.OOAnalyzer.analyzeClasses(OOAnalyzer.java:346)
	at ooanalyzer.OOAnalyzerGhidraPlugin$ImportCommand.cmdConfigureAndExecute(OOAnalyzerGhidraPlugin.java:166)
	at ooanalyzer.OOAnalyzerGhidraPlugin$ImportCommand.applyTo(OOAnalyzerGhidraPlugin.java:99)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:832)

```
![image](https://user-images.githubusercontent.com/4720007/105745641-c9039b80-5f3e-11eb-9996-90d67a382d3c.png)

[bug.txt](https://github.com/cmu-sei/pharos/files/5868549/SHCReplay.dll-ooprog-results-bug.txt)

**Comment by sei-eschwartz** [comment] 2021-01-25 19:28
Thank you for the report.  Is it possible that you have a namespace that ends with the string `"::"`?

**Comment by gynt** [comment] 2021-01-25 19:49
> Thank you for the report. Is it possible that you have a namespace that ends with the string `"::"`?

No, there is no such namespace (searched all occurrences of `::`).
I attached the file to the original post in case someone wants to trace it back.

**Comment by sei-eschwartz** [comment] 2021-01-25 19:55
I pushed a branch [here](https://github.com/sei-eschwartz/pharos/tree/issue_160) to hopefully fix the issue and shed light on where the problem is coming from.

You can download the built plugin from [Azure](https://dev.azure.com/seipharos/pharos/_build/results?buildId=299&view=results) if you want or build it yourself.  The git version is not quite done yet.

Please let me know if this allows you to import.  Either way, it would be helpful to look for "Normalize name ending in ::" lines in your Ghidra `application.log` file.

**Comment by gynt** [comment] 2021-01-25 19:57
Yes I noticed :) Will do, was waiting for the git one, but maybe I will try in 9.2.1 as I have that version too. Ah okay, was about to ask where I can find the `warn` output. Thanks!

**Comment by gynt** [comment] 2021-01-25 20:38
So... I ran the git version from Azure, and now it runs without error (because the exception was resolved and turned into a warning).

The whole log is +50MB, so I am sharing a snippet from the point where it started spitting: `Got namespace from Ghidra demangler: System::  ` which I thought might be a clue.

```stacktrace
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Trying to demangle ?GetCreationTime@File@IO@System@@SA?AU_FILETIME@@PB_W@Z using Ghidra  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Ghidra demangled ?GetCreationTime@File@IO@System@@SA?AU_FILETIME@@PB_W@Z to System::IO::Fi  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Got namespace from Ghidra demangler: System::  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Trying to demangle cls_0x1000a050 using Ghidra  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Ghidra did not know how to demangle cls_0x1000a050  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Trying to demangle ?CreateDirectory@Directory@IO@System@@SAXABV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z using Ghidra  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Ghidra demangled ?CreateDirectory@Directory@IO@System@@SAXABV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z to System::IO::Directo  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Got namespace from Ghidra demangler: System::  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Trying to demangle cls_0x1000a060 using Ghidra  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Ghidra did not know how to demangle cls_0x1000a060  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Trying to demangle ?Close@FileStream@IO@System@@UAEXXZ using Ghidra  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Ghidra demangled ?Close@FileStream@IO@System@@UAEXXZ to System::IO::FileStre  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Got namespace from Ghidra demangler: System::  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Trying to demangle cls_0x1000a064 using Ghidra  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Ghidra did not know how to demangle cls_0x1000a064  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Trying to demangle ??0IOException@IO@System@@QAE@PB_W@Z using Ghidra  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Ghidra demangled ??0IOException@IO@System@@QAE@PB_W@Z to System::IO::IOExcepti  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Got namespace from Ghidra demangler: System::  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Trying to demangle cls_0x1000a128 using Ghidra  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Ghidra did not know how to demangle cls_0x1000a128  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Trying to demangle ??0MemoryStream@IO@System@@QAE@PAXH@Z using Ghidra  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Ghidra demangled ??0MemoryStream@IO@System@@QAE@PAXH@Z to System::IO::MemoryStre  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Got namespace from Ghidra demangler: System::  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/std  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/std  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/std  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/System  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/System/IO  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/SHCReplay  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/SHCReplay  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/SHCReplay  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/SHCReplay  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/SHCReplay  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/std  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/std  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/stdext  
2021-01-25 21:32:44 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/std  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/stdext  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 21:32:45 WARN  (OOAnalyzer) Normalize name ending in ::? System::  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/System__  
2021-01-25 21:32:45 WARN  (OOAnalyzer) Normalize name ending in ::? System::  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/System__  
2021-01-25 21:32:45 WARN  (OOAnalyzer) Normalize name ending in ::? System::  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/System__  
2021-01-25 21:32:45 WARN  (OOAnalyzer) Normalize name ending in ::? System::  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/System__  
2021-01-25 21:32:45 WARN  (OOAnalyzer) Normalize name ending in ::? System::  
2021-01-25 21:32:45 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/System__  
2021-01-25 21:32:45 INFO  (OOAnalyzer) 38 types selected out of 38 defined in OOAnalyzer JSON file.  
```

**Comment by sei-eschwartz** [comment] 2021-01-25 20:46
It looks like the problem is coming from around here: https://github.com/cmu-sei/pharos/blob/9983bdcdc271e661a6045ce22d827c7be339d409/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java#L1638

I have a theory.  Ghidra used to leave a :: at the end of the namespace.  Perhaps this is now fixed, so we chopped off the IO in `System::IO`.

**Comment by gynt** [comment] 2021-01-25 20:49
Yes I think you could consistently reproduce this if you define `System::IO` namespaces and import those :)

**Comment by sei-eschwartz** [comment] 2021-01-25 20:53
If you wouldn't mind testing with [this](https://dev.azure.com/seipharos/pharos/_build/results?buildId=301&view=results) when it finishes building I would appreciate it.  I am pretty sure that is what the problem is though.

**Comment by gynt** [comment] 2021-01-25 21:57
Some of it is still offcut in the log, but the code seems to run fine now. Here is the log with my comments:

```
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Trying to demangle ?GetCreationTime@File@IO@System@@SA?AU_FILETIME@@PB_W@Z using Ghidra  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Ghidra demangled ?GetCreationTime@File@IO@System@@SA?AU_FILETIME@@PB_W@Z to System::IO::Fi  <-- this is still offcut by 2 characters
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Got namespace from Ghidra demangler: System::IO  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Trying to demangle cls_0x1000a050 using Ghidra  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Ghidra did not know how to demangle cls_0x1000a050  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Trying to demangle ?GetFiles@Directory@IO@System@@SA?AV?$vector@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V?$allocator@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@2@@std@@PB_W0@Z using Ghidra  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Ghidra demangled ?GetFiles@Directory@IO@System@@SA?AV?$vector@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V?$allocator@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@2@@std@@PB_W0@Z to System::IO::Directo  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Got namespace from Ghidra demangler: System::IO  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Trying to demangle cls_0x1000a060 using Ghidra  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Ghidra did not know how to demangle cls_0x1000a060  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Trying to demangle ?Close@FileStream@IO@System@@UAEXXZ using Ghidra  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Ghidra demangled ?Close@FileStream@IO@System@@UAEXXZ to System::IO::FileStre  <-- this is still offcut by 2 characters
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Got namespace from Ghidra demangler: System::IO  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Trying to demangle cls_0x1000a064 using Ghidra  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Ghidra did not know how to demangle cls_0x1000a064  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Trying to demangle ??0IOException@IO@System@@QAE@PB_W@Z using Ghidra  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Ghidra demangled ??0IOException@IO@System@@QAE@PB_W@Z to System::IO::IOExcepti  <-- this is still offcut by 2 characters
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Got namespace from Ghidra demangler: System::IO  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Trying to demangle cls_0x1000a128 using Ghidra  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Ghidra did not know how to demangle cls_0x1000a128  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Trying to demangle ??0MemoryStream@IO@System@@QAE@PAXH@Z using Ghidra  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Ghidra demangled ??0MemoryStream@IO@System@@QAE@PAXH@Z to System::IO::MemoryStre  <-- this is still offcut by 2 characters
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Got namespace from Ghidra demangler: System::IO  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/std  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/std  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/std  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/System  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/System/IO  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/SHCReplay  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/SHCReplay  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/SHCReplay  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/SHCReplay  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/SHCReplay  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/std  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/std  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/stdext  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/std  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/stdext  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/System/IO  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/System/IO  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/System/IO  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/System/IO  
2021-01-25 22:55:47 DEBUG (OOAnalyzer) Final category path name: /OOAnalyzer/System/IO  
2021-01-25 22:55:47 INFO  (OOAnalyzer) 38 types selected out of 38 defined in OOAnalyzer JSON file.  
```

**Comment by gynt** [comment] 2021-01-25 21:59
... and these offcut namespaces are a problem:

![image](https://user-images.githubusercontent.com/4720007/105771495-ed706f80-5f60-11eb-9872-57e24ea40ad2.png)

**Comment by sei-eschwartz** [comment] 2021-01-25 23:09
I found another instance where we assumed there was a trailing `::`.  If you don't mind testing [again](https://dev.azure.com/seipharos/pharos/_build/results?buildId=302&view=results) I'd appreciate it!

**Comment by gynt** [comment] 2021-01-26 12:34
I cannot spot anything wrong inside Ghidra, except that the log has a warning and an error. The warning seems to be related to my issue:

```stacktrace
2021-01-26 13:29:18 DEBUG (OOAnalyzer) Using symbol name OOAnalyzer::SHCReplay::ReplayCommand::virt_meth_0x10006870 instead of function name virt_meth_0x10006870  
2021-01-26 13:29:18 ERROR (OOAnalyzer) There is no virtual function table at address 0x1000a590  
2021-01-26 13:29:18 DEBUG (OOAnalyzer) Using symbol name OOAnalyzer::SHCReplay::ReplayMeta::~ReplayMeta instead of function name ~ReplayMeta  
2021-01-26 13:29:18 DEBUG (OOAnalyzer) Using symbol name OOAnalyzer::SHCReplay::ReplayMeta::virt_meth_0x10006d20 instead of function name virt_meth_0x10006d20  
2021-01-26 13:29:18 DEBUG (OOAnalyzer) Using symbol name OOAnalyzer::SHCReplay::ReplayMeta::virt_meth_0x10006dd0 instead of function name virt_meth_0x10006dd0  
2021-01-26 13:29:18 DEBUG (OOAnalyzer) Using symbol name OOAnalyzer::SHCReplay::ReplayCommand::virt_meth_0x10006870 instead of function name virt_meth_0x10006870  
2021-01-26 13:29:18 DEBUG (OOAnalyzer) Using symbol name OOAnalyzer::std::_Ref_count_obj2<class_SHCReplay::ReplayCommand>::virt_meth_0x10006330 instead of function name virt_meth_0x10006330  
2021-01-26 13:29:18 DEBUG (OOAnalyzer) Using symbol name OOAnalyzer::type_info::~type_info instead of function name ~type_info  
2021-01-26 13:29:18 WARN  (OOAnalyzer) Unable to create label: ghidra.util.exception.InvalidInputException: Invalid parent namespace specified for new Label symbol: SHCHUB.DLL::System::IO::IOException  
2021-01-26 13:29:18 DEBUG (OOAnalyzer) Using symbol name FUN_100011c0 instead of function name FUN_100011c0  
2021-01-26 13:29:18 DEBUG (OOAnalyzer) Using symbol name OOAnalyzer::System::Exception::virt_meth_0x100011c0 instead of function name virt_meth_0x100011c0  
```

**Comment by sei-eschwartz** [comment] 2021-01-26 15:09
I think this warning is probably an unrelated problem.  Ghidra is very defensive about imported namespaces.  We probably try to make a label there for a vftable and fail.

**Comment by gynt** [comment] 2021-01-26 19:03
I guess my issue is solved! Thanks for the quick help!

**Closed** 2021-02-02 02:43 UTC
Labels: bug, fix pending merge, plugins
