### ISSUE TITLE
setupapi.dll missing from APIDB

### ISSUE THREAD

**Issue by janbbeck** [cmu-sei/pharos#86] opened 2020-05-15 07:46 UTC
I see the following warning:
```
APID[WARN ]: API database has no data for DLL: SETUPAPI
APID[TRACE]: API Lookup: SETUPAPI:SetupDiEnumDeviceInterfaces
```
does that mean `SetupDiEnumDeviceInterfaces` should be in the function database, but is missing? 
It seems like it should be expected in setupapi.dll:
https://docs.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdienumdeviceinterfaces

There are some other examples of windows apis missing, but I would like feedback as to whether you guys want that reported before I spam those here...

**Comment by sei-eschwartz** [comment] 2020-05-15 12:26
It looks like the API database doesn't have any information on setupapi.dll.  I also confirmed that the newer version we are working on also does not contain that dll.

**Comment by sei-ccohen** [comment] 2020-05-15 14:55
We're still trying to figure out how well our API database design scales.  There are a lot of DLLs in the world, and there's no obvious way to determine which ones are most widely used and therefore warrant inclusion in the standard database.  On the other hand I think it's equally clear that we'd like for the API data to be as comprehensive as possible, because it has lots of value in applications beyond just OOAnalyzer.  For example, a Ghidra plugin that causes proper type propagation based on parameter types from external APIs would be very valuable for analysts.

In summary, we're happy to receive submissions of API data in JSON format, but we haven't decided  whether we'll include all DLLs in the standard Pharos database just yet.  Regardless, a pull request containing API database in JSON format would be visible to other users, and easily added to a configuration on an ad-hoc basis, so it's likely to benefit others regardless of what we decide to do.   Our internal mechanism that we use to build the existing database cab be easily extended to generate data for other DLLs, but it may need some work before being released publicly.

**Comment by janbbeck** [comment] 2020-05-16 06:06
Hmm, ok so with respect to which dlls to include, I would humbly suggest a policy of at least including all microsoft shipped ones.

With respect to setupapi.dll, should I work on a JSON file and submit it? I am not sure a pull request that never gets acted upon is really visible to anyone. I certainly did not look through pull requests to see if there is a json file. Or did I misunderstand what you are trying to say?

**Comment by sei-ccohen** [comment] 2020-05-26 15:32
We have a process that generates the SQLite API database from a specific windows installation.  When possible, we prefer shipping API data in the SQLite database format because it is much more efficient than the JSON file format.  Unfortunately though, a full set of "all microsoft shipped DLLs" still generates a database that is very large.  It might be a gigabyte or more.   I don't think we've gotten that process to complete for_all_ DLLs. Just adding the full MFC DLL for example increased the size of the existing database from 43MB to 224MB.  We're working through trying to release an improved API database, but it's a human resource issue on our end.

We don't want to discourage you from contributing API database improvements, because I suspect that others who are looking for improved API data may find your JSON files very useful, which is why I suggested that you submit them as a pull request.   We could even accept them as "auxiliary" JSON files, in the main branch if there seems to be any trouble with folks finding them, but longer term our preferred solution is to generate a better SQLite database and ship that.  It's just that it's taking us a while to make that happen because of various database size related concerns.

**Comment by janbbeck** [comment] 2020-05-26 15:40
That is a bit strange since the json file for mfc42.dll is only about 3.8MB. But for now I did a PR #88 to place those json files I made into apidb. They are easy to find for anyone looking at the json example already there.

**Comment by sei-mwd** [comment] 2020-05-28 03:01
Merged #88

**Closed by sei-mwd** 2020-05-28 03:01 UTC
Labels: enhancement

**Comment by Phylante** [comment] 2020-12-29 21:33
Hello,
regarding json api data that was created for PR #88 , do you @janbbeck, remember how you automated the creation of the json files ?  
This could be helpful for users that want to create their own json files.
Thank you in advance.

**Comment by janbbeck** [comment] 2020-12-29 21:41
Yeah, I described it here:
https://www.janbeck.com/cybersecurity-and-reverse-engineering-fun/ooanalyzer-a-big-help-for-reversing-object-oriented-binaries

**Comment by Phylante** [comment] 2020-12-29 22:48
This was really useful.   
Thank you

**Comment by janbbeck** [comment] 2020-12-29 23:01
Any time. Glad it helped someone.
