### ISSUE TITLE
Very long analysis and important drift between expected blocks & functions counts

### ISSUE THREAD

**Issue by cpainchaud** [cmu-sei/pharos#60] opened 2020-02-04 15:41 UTC
Hi,

 So I had this one running for 9 hours now and while it seemed to progress very fast until 90% mark, it's now progressing quite very slow. what strikes me if the different between expected bytes, blocks and functions which more than doubled for functions for example:

root@339ab94ee21f:/tmp/share# ooanalyzer --maximum-memory 0 --per-function-timeout 0 --partitioner-timeout 0 --timeout 0 --json ida.json -F facts.txt -R results.txt xxxx.exe
OPTI[INFO ]: Analyzing executable: exe.exe
OPTI[INFO ]: OOAnalyzer version 1.0.
OPTI[INFO ]: ROSE stock partitioning took 5317.74 seconds.
OPTI[INFO ]: Partitioned 14033584 bytes, 4963808 instructions, 994447 basic blocks, 534 data blocks and 76710 functions.
PRT2[MARCH]: cfg:  91% [##############-] 16968921 bytes 1209943 blks 172878 funcs

Now at every tick I can see 5-15 bytes were processed and functions count increments by one as well as block count and memory consumption is progressing very slowly as well.

I am running latest version your docker auto build.

Is there anything wrong? At that rate I did calculate that it would finish a few weeks. Thank you in advance for your advices.

**Comment by sei-ccohen** [comment] 2020-02-04 16:04
Sorry to hear that you're having partitioner troubles.   One option would be to specify --partitioner=rose, which would have terminated the partitioning after 5317.74 seconds, and skipped the "slow part".   To the extent that you wanted the additional functions being detected in our custom partitioner extensions (which are usually code blocks like thunks, exception handlers, etc.)  you probably just have to wait. :-(

This very slow partitioning behavior is caused by an expensive round trip from Pharos into ROSE and back.  The problem seems to be related to many small blocks that are not contiguous to one another. I thought we had eliminated this problem a couple of months ago, but perhaps not.  One possibility is that the docker container you're running didn't get that fix, but I think that's very unlikely.   Would you be willing to share the executable as a test case?

**Comment by cpainchaud** [comment] 2020-02-04 16:30
Hi and thank you for your reply,

 Just to be clear, I followed these instruction yesterday:
- docker pull seipharos/pharos
- docker run --rm -it -v /dir:/dir seipharos/pharos

I am assuming it should have latest code from prebuilt images (am I wrong?)

I can share the EXE to email cfc@cert.org? GDrive link ok?

I will run another instance with the partitioner=rose and see how it goes (and it will be interesting to see see if it spots lots of differences with the 'longer' one)

**Comment by sei-ccohen** [comment] 2020-02-04 18:44
I believe that the docker images are current with the latest commits.  It's just that a colleague handles that and I can't explain why this partitioner issue is back again...  Yes, email for the problematic executable would be fine.

**Comment by sei-eschwartz** [comment] 2020-02-04 19:06
The docker images are up-to-date with the github source code.

**Comment by sei-eschwartz** [comment] 2020-04-27 12:42
@sei-ccohen Did you ever receive the EXE?  @cpainchaud Did you try the ROSE partitioner?

**Comment by cpainchaud** [comment] 2020-04-27 12:58
yes we tried a few things but size seems to be the big challenge here in many ways

**Comment by sei-eschwartz** [comment] 2020-04-27 13:10
It sounds like there is no action to be taken then for this issue, so I'm going to close it.

**Closed by sei-eschwartz** 2020-04-27 13:10 UTC

**Comment by sei-ccohen** [comment] 2020-06-03 21:41
Because this issue involved the analysis of a large executable, I encourage you to review the recently release documentation about [best practices for analyzing large programs](https://github.com/cmu-sei/pharos/tree/master/share/prolog/oorules).
