### ISSUE TITLE
OOAnalyzer doesn't support kext files

### ISSUE THREAD

**Issue by jobermayr** [cmu-sei/pharos#62] opened 2020-02-19 18:28 UTC
Used revision: 2ff59e7

`$ ooanalyzer -j test.json test`
`OPTI[INFO ]: Analyzing executable: test`
`OPTI[INFO ]: OOAnalyzer version 1.0.`
`OOAN[FATAL]: Pharos main error: unrecognized file format for "test": Mach-O 64-bit x86_64 kext bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>`
`$ `

**Comment by sei-ccohen** [comment] 2020-02-19 20:04
Pharos relies on ROSE for it's executable container parsing support, although we've contributed to the ROSE capability.  Unfortunately ROSE doesn't currently support Mach-O executables, even though Pharos builds on the MacOS platform.   This is true for all Pharos tools.   Additionally the OOAnalyzer tool really only supports 32-bit Windows executables, because there is a fair bit of Prolog rule logic that is specific to that compiler.  Conceptually OOAnalyzer could be "ported" to support other OO compilers and some progress on that has been made, but it's not working yet. 

Closing this issue as a duplicate of this [issue](https://github.com/cmu-sei/pharos/issues/49).  you can find more details there as well.

**Closed by sei-ccohen** 2020-02-19 20:04 UTC
