### ISSUE TITLE
Sanity check failure during Prolog Analysis : Contradictory information about merging classes

### ISSUE THREAD

**Issue by gwgill** [cmu-sei/pharos#136] opened 2020-09-24 00:09 UTC
Tail of log is:

> reasonForwardAsManyTimesAsPossible complete.
> Entering stage 'Initial reasoning complete'.
> failed.
> Consistency checks failed.
> Contradictory information about merging classes: Method1=0x102f2528 Method2=0x102f24e4
> Initial sanity check failed, indicating the OO rules are incorrect.
> Please report this failures to the Pharos developers!

If you would like the facts.pl to reproduce the failure, please contact me.

**Comment by sei-eschwartz** [comment] 2020-09-24 00:18
Yes please share the facts file.  If you can share the executable that would help  too.

Sent from Workspace ONE Boxer

On Sep 23, 2020 8:09 PM, gwgill <notifications@github.com> wrote:

Tail of log is:

reasonForwardAsManyTimesAsPossible complete.
Entering stage 'Initial reasoning complete'.
failed.
Consistency checks failed.
Contradictory information about merging classes: Method1=0x102f2528 Method2=0x102f24e4
Initial sanity check failed, indicating the OO rules are incorrect.
Please report this failures to the Pharos developers!

If you would like the facts.pl to reproduce the failure, please contact me.

**Comment by gwgill** [comment] 2020-09-24 00:41
You will have to contact me (via email).

**Comment by sei-eschwartz** [comment] 2020-09-24 12:03
I don't know your email address.  Can you email me at eschwartz@cert.org?

**Comment by sei-eschwartz** [comment] 2020-09-25 12:08
I just ran from scratch (from the exe, did not use your facts) and completed successfully.  I'll try running from your facts file now.

Do you remember what command lines you used?

**Comment by sei-eschwartz** [comment] 2020-09-25 12:13
I was able to reproduce from your facts file, so I can investigate from there.

**Comment by sei-ccohen** [comment] 2020-09-25 15:19
So I looked at the differences in the fact files generated by sei-eschwartz and the fact file generated by you.  You have about 358,000 facts, while sei-eschwartz has about 504,000 facts.   The differences are roughly proportional across all fact types, so that suggests to me that your analysis of the executable "got tired and gave up".    Without the log file, it's not really possible for me to say exactly why that happened.

I suggest that you review your log file, looking specifically for errors about timeouts, memory shortages,  and missing function summaries.   If there are a bunch of repeating messages near the end of the executable analysis phase, they should help explain what happened.   My theories include things like:  Your computer is slower than ours, and more functions exceeded the per-function timeout.  Or maybe you have less RAM, and started having memory shortage problems.  The system is designed to be "resilient" in the sense that it will muddle forward, and attempt to do the best that it can.   In this case, that wasn't good enough, because it seems to have triggered an "internal error" in the Prolog phase.   For example, our facts file had one "purecall" fact and yours did not.   That fact can be pretty important for preventing internal errors, but it did not seem to be the sole cause of the problem.

If you're unable to sort out what happened from the log file, or get a new facts file with a fact count closer to 504,000 facts, please send us the log from the OOAnalyzer step, and we can help figure out what happened.

**Comment by gwgill** [comment] 2020-09-26 02:45
OK - thanks for the analysis. Yes, the computer I'm using doesn't have vast amounts of memory (it's a Linux VM running on my Mac laptop), and my initial runs failed when it ran out of swap. But I saw no such signs of running out of swap once I Bumped it up to 15 Gb, so I'm a little puzzled as to why the resulting facts file are different to yours. I'll try running it again and see if I can spot something (perhaps there were timeouts that I didn't notice.)

I did work around the problem by deleting the conflicting addresses from the facts file until the sanity check passed. The workaround would be quicker if all the conflicts were reported before bailing out though. Perhaps an option to automatically remove conflicting facts ?

**Comment by sei-eschwartz** [comment] 2020-09-26 13:11
I'll send you a copy of the facts and results files that I got so you can compare with yours.

Generally the error you got means that something went very wrong, and it usually makes more sense to figure out what happened than try to continue reasoning.  But we may need to add an option to continue anyway for #135.

**Comment by gwgill** [comment] 2020-09-27 01:18
So I re-ran everything without any limits, and got the same problem. Summary:

Ubuntu 20 in VirtualBox on Mac OS X 10.12.

  docker pull seipharos/pharos

  docker run --rm -it -v /dir:/dir seipharos/pharos

  fn2hash --serialize=ooprog.ser --no-semantics --partitioner=rose ooprog.exe > ooprog.csv

  ooanalyzer --serialize=ooprog.ser --prolog-facts=ooprog-facts.pl --threads=1 ooprog.exe

  ooprolog --facts ooprog-facts.pl --results ooprog-results.pl --log-level=6 > ooprog.log

Resulting facts.pl file of 358136 lines

Contradictory information about merging classes: Method1=0x102f2528 Method2=0x102f24e4

**Comment by sei-eschwartz** [comment] 2020-09-27 11:25
Hmm no-semantics or the rose partitioner may explain the difference in fact files.  This is very helpful, thanks.

Sent from Workspace ONE Boxer

On Sep 26, 2020 9:18 PM, gwgill <notifications@github.com> wrote:

So I re-ran everything without any limits, and got the same problem. Summary:

Ubuntu 20 in VirtualBox on Mac OS X 10.12.

docker pull seipharos/pharos

docker run --rm -it -v /dir:/dir seipharos/pharos

fn2hash --serialize=ooprog.ser --no-semantics --partitioner=rose ooprog.exe > ooprog.csv

ooanalyzer --serialize=ooprog.ser --prolog-facts=ooprog-facts.pl --threads=1 ooprog.exe

ooprolog --facts ooprog-facts.pl --results ooprog-results.pl --log-level=6 > ooprog.log

Resulting facts.pl file of 358136 lines

Contradictory information about merging classes: Method1=0x102f2528 Method2=0x102f24e4

**Comment by sei-eschwartz** [comment] 2020-09-27 17:01
Was able to reproduce with `--no-semantics --partitioner=rose`

**Comment by sei-ccohen** [comment] 2020-09-27 17:12
Both the --no-semantics and --partioner=rose options _reduce_ the accuracy of OOAnlayzer but improve the performance, which is why they were recommended in the documentation about analyzing large files.   If you're able to run the analysis in your environment on your executable without those options, I encourage you to do so.   We'll continue to investigate exactly what went wrong that prevented a valid set of facts from being generated with these options, but I can already think of several reasons why these options would have produced significantly fewer facts.

The two options are completely independent of one another.   If removing both options proves to be too slow, I think the --partitioner=rose is the more likely cause of the problems that you're seeing.   OO programs with large numbers of methods that are only called virtually can be missed entirely in the standard ROSE partitioner, and that's consistent with what you seem to be experiencing.

**Comment by sei-ccohen** [comment] 2020-09-28 16:43
I'm fairly certain that the RTTI information in this file is not reliable.   It would have us to believe that every class in the file shares the same VFTable!  I've confirmed that does not appear to be an analysis failure on the part of OOAnalyzer, but rather something unusual occurring in the file itself.   I recommend using --rtti=false when running the OOProlog step.

I spot-checked about a dozen functions that appeared in the larger facts file that did not appear in the smaller facts file.   In every case, Ghidra did not make code at that address by default either.   The difference between --partitioner=ROSE and our partitioner extensions is that we attempt to make code and then subsequently analyze that code for functions that appear in "gaps" between other code.  In short, it looks _very_ likely to me that your problem with the number of facts is related to this option, and that you have no choice but to wait for the slower partitioning if you want a complete set of facts.

Finally, I'd like to point out that since the file is a DLL you may encounter additional analysis problems, depending on the behavior of the program being analyzed.   Sometimes, DLLs lack sufficient interaction between the classes within the DLL for OOAnalyzer to recover meaningful classes.  For example, imagine a DLL that has many classes, but no calls to any constructors and almost no calls between the classes because the DLL expects that the program linking against the DLL will instantiate the objects and call various methods as needed.   In this case, OOAnalyzer is missing the critical information needed.   Not all DLLs behave this way, but it may be worth a little manual analysis to form a judgment about whether this is likely to be a significant problem in your DLL.

**Comment by sei-ccohen** [comment] 2020-09-28 17:38
My apologies.  I was misinterpreting the RTTI data structures because my notes about the RTTI data structures in the facts.pl file were confusing. ;-(   I have no reason to believe that the RTTI is corrupt.   the other two points are still valid (to my knowledge).

**Comment by gynt** [comment] 2020-10-07 12:23
Hi all, I am getting a very similar error:
```console
Contradictory information about merging classes: Method1=0x5a6510 Method2=0x5a61fc
Initial sanity check failed, indicating the OO rules are incorrect.
Please report this failures to the Pharos developers!
```
I do not get the error if I set `--partitioner=rose`. 
I am running the latest version from GitHub (compiled from source). Without `--partitioner=rose`, I get these warnings and errors as well:
```console
OOAN[WARN ]: Call descriptor at 538AB0: farCall   5387, 41005380 has 2 operands, skipping
OOAN[WARN ]: Call descriptor at 538B30: farCall   5387, 41005380 has 2 operands, skipping
OOAN[WARN ]: Call descriptor at 538C50: farCall   5387, 41005380 has 2 operands, skipping
OOAN[WARN ]: Call descriptor at 5392CC: farCall   5387, 41005380 has 2 operands, skipping
OOAN[WARN ]: Call descriptor at 539484: farCall   5382, 65005380 has 2 operands, skipping
OOAN[WARN ]: Call descriptor at 539730: farCall   5387, 41005380 has 2 operands, skipping
OOAN[WARN ]: Call descriptor at 5398D8: farCall   5381, -5FFAC80 has 2 operands, skipping
OOAN[WARN ]: Call descriptor at 53995C: farCall   5387, -74FFAC80 has 2 operands, skipping
OOAN[WARN ]: Call descriptor at 5399DC: farCall   5388, F005380 has 2 operands, skipping
OOAN[WARN ]: Call descriptor at 539A64: farCall   5388, 59005380 has 2 operands, skipping
OOAN[WARN ]: Call descriptor at 539AE4: farCall   5387, 41005380 has 2 operands, skipping
OOAN[WARN ]: Call descriptor at 539B64: farCall   5387, 41005380 has 2 operands, skipping
OOAN[WARN ]: Successor 0x00498D07 of 498D05: sub       al, 3 not found.
OOAN[WARN ]: Instruction 4BB1B8: jmp       [4BB284+eax*4] had incomplete successors.
OOAN[WARN ]: Instruction 4FF9F9: jmp       [4FFAAC+edx*4] had incomplete successors.
OOAN[WARN ]: Instruction 5386F2: jmp       [5398B8+ecx*4] had incomplete successors.
OOAN[WARN ]: No fallthru edge for call at 0x00538AB0
OOAN[WARN ]: No fallthru edge for call at 0x00538B30
OOAN[WARN ]: No fallthru edge for call at 0x00538C50
OOAN[WARN ]: No fallthru edge for call at 0x005392CC
OOAN[WARN ]: Successor 0x00539351 of 53934D: adc       [ebx+0], 65 not found.
OOAN[WARN ]: No fallthru edge for call at 0x00539484
OOAN[WARN ]: No fallthru edge for call at 0x00539730
OOAN[WARN ]: No fallthru edge for call at 0x005398D8
OOAN[WARN ]: No fallthru edge for call at 0x0053995C
OOAN[WARN ]: No fallthru edge for call at 0x005399DC
OOAN[WARN ]: No fallthru edge for call at 0x00539A64
OOAN[WARN ]: No fallthru edge for call at 0x00539AE4
OOAN[WARN ]: No fallthru edge for call at 0x00539B64
OOAN[ERROR]: Unable to find fallthru edge for call at 0x00538AB0
OOAN[ERROR]: Unable to find fallthru edge for call at 0x00538B30
OOAN[ERROR]: Unable to find fallthru edge for call at 0x00538C50
OOAN[ERROR]: Unable to find fallthru edge for call at 0x005392CC
OOAN[ERROR]: Unable to find fallthru edge for call at 0x00539484
OOAN[ERROR]: Unable to find fallthru edge for call at 0x00539730
OOAN[ERROR]: Unable to find fallthru edge for call at 0x005398D8
OOAN[ERROR]: Unable to find fallthru edge for call at 0x0053995C
OOAN[ERROR]: Unable to find fallthru edge for call at 0x005399DC
OOAN[ERROR]: Unable to find fallthru edge for call at 0x00539A64
OOAN[ERROR]: Unable to find fallthru edge for call at 0x00539AE4
OOAN[ERROR]: Unable to find fallthru edge for call at 0x00539B64
```
Without that option I do not obtain any of the above errors and warnings, but I obtain twice the amount of facts compared to with that option (which makes sense from an accuracy or aggressiveness point of view).

**Comment by sei-eschwartz** [comment] 2020-10-07 12:30
@gynt Can you open a new issue?  Please share your executables and/or facts files if possible.

**Comment by sei-ccohen** [comment] 2020-10-08 21:36
For the initial reporter, if I'm tracking this ticket correctly, I think the most recent commit fixes your test case.  For gynt's problem in a new ticket, I believe that it does not.

**Comment by sei-eschwartz** [comment] 2020-10-09 12:33
Still not fixed for `--no-semantics --partitioner=rose`.

`Contradictory information about merging classes: Method1=0x102f2518 Method2=0x102f5cfc`

**Comment by sei-eschwartz** [comment] 2020-10-21 12:09
This is fixed now, even for `--no-semantics --partitioner=rose`

**Closed by sei-eschwartz** 2020-10-21 12:09 UTC
Labels: bug, prolog
