### ISSUE TITLE
Stuck at 1% for around an hour when running ooanalyzer

### ISSUE THREAD

**Issue by SeleDreams** [cmu-sei/pharos#78] opened 2020-05-01 17:48 UTC
I noticed while trying to run ooanalyzer using the public docker image, that the process stays stuck at 1% everytime for more than an hour without ever progressing 
![image](https://user-images.githubusercontent.com/16335601/80827829-a11c1d00-8be4-11ea-98ab-ab3511bd583c.png)
I tried it two times and it still didn't change, I can't really tell what went wrong in particular, any ideas ?

**Comment by cfcohen** [comment] 2020-05-01 21:06
First, I should volunteer that by "highly experimental" we really mean "doesn't actually work".   So specifying --allow-64bit is your primary problem for getting useful results.  OOAnalyzer really only supports 32-bit Windows programs right now.  The --allow-64bit option is for folks who are trying to make it work for 64bit executables.

This is clearly a partitioning problem, although I don't understand what the problem is exactly.   The bug is most likely in the upstream  ROSE partitioning code based on what I can tell from your messages.   You can specify --pdebug to enable the ROSE debugging for the partitioner, which will produce a _lot_ of detail about what's actually going on.  It's possible that ROSE has entered some kind of (endless?) loop which would be an interesting bug.  It's also possible that the input file is just quite large, and there's something a little wrong with the progress bar, although I would have expected it to at least tick up to a few percent after an hour, depending on how fast your machine is.

Specifying --no-semantics may help because the "bug" may be in semantic evaluation of basic blocks during partitioning.  Using --no-semantics will also be much faster, which is important on a large file like this one.

**Comment by SeleDreams** [comment] 2020-05-01 22:48
![image](https://user-images.githubusercontent.com/16335601/80847065-95455080-8c0e-11ea-8517-7a728fbc8e3d.png)
After enabling the debug printing this is where it gets stuck and doesn't progress any further

**Comment by sei-eschwartz** [comment] 2020-05-01 22:50
And with --no-semantics?

**Comment by SeleDreams** [comment] 2020-05-01 22:50
I didn't try yet, I'm going to try

**Comment by SeleDreams** [comment] 2020-05-01 23:15
![image](https://user-images.githubusercontent.com/16335601/80848121-6af59200-8c12-11ea-825c-0c6e9ee26f54.png)
it seems to get stuck at the same place

**Comment by SeleDreams** [comment] 2020-05-01 23:17
[Application.zip.txt](https://github.com/cmu-sei/pharos/files/4566599/Application.zip.txt)
this is the exe if you want to check (remove the txt from the name, it was required to be able to post it)

**Comment by cfcohen** [comment] 2020-05-02 16:43
I'm still not sure what's happening here.  Using the file you supplied, the following command:

```ooanalyzer --json=/dev/null --allow-64bit --no-semantics --partitioner=rose --maximum-memory 40000 Application.exe```

completed the partitioning phase in about 860 seconds on my machine.   It appears that somehow you've gotten a bad build of ROSE or something.  Since it's our public docker image I'll kick the issue back over sei-eschwartz to see if he has any ideas about why the docker results might differ from my build.  Maybe there's a memory shortage?  This file quickly used a little more than 20GB for partitioning (ROSE disassembles the entire file into memory, which can be a problem for largish executables).

**Comment by SeleDreams** [comment] 2020-05-02 18:57
20gb of memory... ram ? because my pc has 16gb of ram, I didn't expect to need that much ram
if it's space I don't really know as I have more than 20gb free at least

**Comment by sei-eschwartz** [comment] 2020-05-02 20:54
I'll see if I can reproduce this.

**Comment by edmcman** [comment] 2020-05-02 22:47
I was able to reproduce, but it was clear that the container was out of memory and was just swapping like crazy.  So @SeleDreams you will have to allocate more memory to your docker container.  On my machine, the limit is 8GB, and it got farther than yours did, so your memory is probably limited to a smaller amount.  I know on mac the default is only 2GB.

**Comment by SeleDreams** [comment] 2020-05-02 23:00
I see, I'll look at how I could do it
I feel like maybe ooanalyzer could display an error message when there isn't enough memory to make it more clear

**Comment by cfcohen** [comment] 2020-05-02 23:36
So I think the real problem here is that the ROSE partitioner loads the entire image disassembly into RAM all at once.   For small files (say less than a megabyte) this isn't a big problem.  For a 17MB executable, each 3-4 byte instruction becomes a fairly large collection of objects with multiple operands, expressions, and so forth.  Then there's the basic block objects, functions, control flow graphs, etc.  We should investigate discarding instruction disassemblies once functions have been completed, but this is more complicated than it sounds because functions evolve as new calls are found and so forth.  For multi-megabyte input executables, multiple gigabytes of RAM are probably just required for right now.

**Comment by SeleDreams** [comment] 2020-05-02 23:42
I wonder if it wouldn't be possible as a solution to instead of loading everything into memory it could write them to a filestream, it would be slower but would at least work

**Comment by sei-eschwartz** [comment] 2020-05-04 14:52
This is an unfortunate situation because Pharos never ran out of memory.  At least for me, I had 1GB of swap, and the container was spending all it's time swapping.  I would welcome a PR for any of these ideas, but I am going to close the issue for now since it sounds like reconfiguring Docker should fix the problem.

**Closed by sei-eschwartz** 2020-05-04 14:52 UTC

**Comment by sei-ccohen** [comment] 2020-06-03 21:40
Because this issue involved the analysis of a large executable, I encourage you to review the recently release documentation about [best practices for analyzing large programs](https://github.com/cmu-sei/pharos/tree/master/share/prolog/oorules).
